
service: cognito-auth

provider:
  name: aws
  runtime: nodejs6.10

functions:
  vehiclesDetail:
    handler: teslaAPIs/teslavehicle.vehiclesDetail
    events:
      - http:
          path: vehiclesDetail
          method: get
          cors: true
          Content-Type: application/json
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:873586173844:userpool/us-west-2_RCOnSMXqU
            claims:
              - email
  chargingState:
    handler: teslaAPIs/chargingstate.chargingState
    events:
      - http:
          path: chargingState
          method: get
          cors: true
          Content-Type: application/json
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:873586173844:userpool/us-west-2_RCOnSMXqU
            claims:
              - email


